feh --bg-scale $HOME/wallpaper.jpg &
picom &
setxkbmap gb &
xss-lock slock &
slstatus &

while true
do
	BRIGHT=$(xbacklight | awk '{printf \"%0.0f\",$1}')
	VOL=$(amixer sget Master | grep % | head -1 | awk '{print $5}' | tr -d '[]')
	TIME=$(date +%a" "%b" "%d" "%H:%M)
	WIFI=$(iwgetid -r | awk '{print $1}')
	BAT=$(acpi -b | awk '{print $4 " " $5}' | tr -d ',')

	xsetroot -name "[☀ $BRIGHT] [  $VOL] [🖧 $WIFI] [☇ $BAT] [$TIME]"
	sleep 0.5s
done &


exec dwm 
